openapi: 3.1.0

info:
  title: API documentation with Swagger
  description: Project starter for API documentation
  version: 0.1.9

servers:
  - url: http://localhost:3000/api/v1
    description: localhost version of API server
  - url: https://localhost:3000/api/v1
    description: localhost version of API server with SSL

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /instagram:
    get:
      summary: Returns an instance of instagram
      description: Instance of instagram
      responses:
        '200':
          description: A Json Object of Instagram
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string